// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb5ThQ-ytLHhN5Y4GyQNQyvvvZKY9fQQ8',
    appId: '1:28169414258:web:87b42fc6386d514b70c4eb',
    messagingSenderId: '28169414258',
    projectId: 'shop-ease-13fb5',
    authDomain: 'shop-ease-13fb5.firebaseapp.com',
    databaseURL: 'https://shop-ease-13fb5-default-rtdb.firebaseio.com',
    storageBucket: 'shop-ease-13fb5.appspot.com',
    measurementId: 'G-N6DEBJXMS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArm_aLy90eokRrs7XdE9hdFfM1MzY3yJk',
    appId: '1:28169414258:android:aeceac5a421272b670c4eb',
    messagingSenderId: '28169414258',
    projectId: 'shop-ease-13fb5',
    databaseURL: 'https://shop-ease-13fb5-default-rtdb.firebaseio.com',
    storageBucket: 'shop-ease-13fb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABGAZnmPsxjO0W989bNxE_7EkkIMIcKQ8',
    appId: '1:28169414258:ios:56659a72af57ca8e70c4eb',
    messagingSenderId: '28169414258',
    projectId: 'shop-ease-13fb5',
    databaseURL: 'https://shop-ease-13fb5-default-rtdb.firebaseio.com',
    storageBucket: 'shop-ease-13fb5.appspot.com',
    androidClientId: '28169414258-h953f21jl3puvndhu8bm0fj5g74ibpfg.apps.googleusercontent.com',
    iosClientId: '28169414258-upnu3m1ffr34vhdhg2u4h03bg5041i99.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendeasyadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABGAZnmPsxjO0W989bNxE_7EkkIMIcKQ8',
    appId: '1:28169414258:ios:56659a72af57ca8e70c4eb',
    messagingSenderId: '28169414258',
    projectId: 'shop-ease-13fb5',
    databaseURL: 'https://shop-ease-13fb5-default-rtdb.firebaseio.com',
    storageBucket: 'shop-ease-13fb5.appspot.com',
    androidClientId: '28169414258-h953f21jl3puvndhu8bm0fj5g74ibpfg.apps.googleusercontent.com',
    iosClientId: '28169414258-upnu3m1ffr34vhdhg2u4h03bg5041i99.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendeasyadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb5ThQ-ytLHhN5Y4GyQNQyvvvZKY9fQQ8',
    appId: '1:28169414258:web:18419319a84e082370c4eb',
    messagingSenderId: '28169414258',
    projectId: 'shop-ease-13fb5',
    authDomain: 'shop-ease-13fb5.firebaseapp.com',
    databaseURL: 'https://shop-ease-13fb5-default-rtdb.firebaseio.com',
    storageBucket: 'shop-ease-13fb5.appspot.com',
    measurementId: 'G-5YKJGMZFST',
  );
}
